"""
src/api/auth/email.py
=====================
Email delivery for authentication flows (verification + password reset).

PROVIDER: Resend (resend.com)
    - Simple REST API, generous free tier (3,000 emails/month)
    - Python SDK: `resend` package
    - Requires RESEND_API_KEY and RESEND_FROM_EMAIL environment variables

GRACEFUL DEGRADATION:
    If RESEND_API_KEY is not set (dev/CI environment), email sending is
    SKIPPED and the token is PRINTED to the log at INFO level.
    This means a fresh clone needs zero email configuration to test registration.

FUNCTIONS
---------
    send_verification_email(email, token)   — 24-hour click-to-verify link
    send_password_reset_email(email, token) — 1-hour reset link

SECURITY NOTES
--------------
    - Tokens are generated by the caller (auth/router.py) as URL-safe random
      strings. This module only formats and sends — it does NOT generate tokens.
    - The email contains the full verification URL, not just the token, so the
      user clicks a link rather than copying a code (reduces phishing risk for
      non-technical users).
    - We use `await asyncio.to_thread(resend.Emails.send, ...)` because the
      Resend Python SDK is synchronous. Running it in a thread prevents blocking
      the async event loop.
"""
from __future__ import annotations

import asyncio
import logging
import os

logger = logging.getLogger(__name__)

_RESEND_API_KEY     = os.getenv("RESEND_API_KEY", "")
_RESEND_FROM_EMAIL  = os.getenv("RESEND_FROM_EMAIL", "DeepCoin <noreply@deepcoin.ai>")
_APP_URL            = os.getenv("APP_URL", "http://localhost:3000")


def _resend_available() -> bool:
    """Check whether the Resend API key is configured."""
    return bool(_RESEND_API_KEY)


async def _send(to: str, subject: str, html: str) -> bool:
    """
    Core email dispatch — wraps the synchronous Resend SDK in a thread.

    WHY asyncio.to_thread:
        The Resend Python SDK makes a synchronous HTTP request. Calling it
        directly in an async route would block the event loop for ~100ms per
        send, stalling all concurrent requests during that window.
        `asyncio.to_thread` offloads it to the thread pool executor, keeping
        the event loop free.

    Returns:
        True if sent successfully, False if Resend raised an exception.
    """
    if not _resend_available():
        logger.info(
            "[EMAIL DEV-MODE] Would send to=%s subject=%r — set RESEND_API_KEY to enable real delivery",
            to, subject,
        )
        return True  # signal success so callers don't enter error paths

    try:
        import resend  # pylint: disable=import-outside-toplevel
        resend.api_key = _RESEND_API_KEY

        def _blocking_send():
            return resend.Emails.send({
                "from":    _RESEND_FROM_EMAIL,
                "to":      [to],
                "subject": subject,
                "html":    html,
            })

        result = await asyncio.to_thread(_blocking_send)
        logger.info("Email sent to=%s id=%s", to, result.get("id", "?"))
        return True

    except Exception as exc:  # pylint: disable=broad-except
        logger.error("Failed to send email to=%s: %s", to, exc)
        return False


async def send_verification_email(to_email: str, token: str) -> bool:
    """
    Send the 24-hour email verification link to a newly registered user.

    WHAT:
        Constructs a link of the form:
            {APP_URL}/verify-email?token={token}
        and sends a branded HTML email with a clickable button.

    WHY 24 hours:
        Long enough for a user who checks email once per day.
        Short enough to limit the window for a stolen/forwarded link.

    Args:
        to_email: Destination email address.
        token:    Opaque random token (URL-safe, stored as hash in DB).

    Returns:
        True if delivery succeeded (or dev-mode skip), False on send error.
    """
    verify_url = f"{_APP_URL}/verify-email?token={token}"

    html = f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family: Arial, sans-serif; background: #0a0f2c; color: #e2e8f0; padding: 40px;">
      <div style="max-width: 520px; margin: auto; background: #131a3a; border-radius: 12px; padding: 40px;">
        <h1 style="color: #3b82f6; margin-bottom: 8px;">DeepCoin</h1>
        <p style="color: #94a3b8; font-size: 13px;">Archaeological Coin Intelligence Platform</p>
        <hr style="border-color: #1e2d52; margin: 24px 0;">
        <h2 style="font-size: 20px; margin-bottom: 12px;">Verify your email address</h2>
        <p style="color: #94a3b8; line-height: 1.6;">
          Thank you for registering. Click the button below to activate your account.
          This link expires in <strong style="color: #e2e8f0;">24 hours</strong>.
        </p>
        <div style="text-align: center; margin: 32px 0;">
          <a href="{verify_url}"
             style="background: #3b82f6; color: white; padding: 14px 32px; border-radius: 8px;
                    text-decoration: none; font-weight: bold; display: inline-block;">
            Verify Email Address
          </a>
        </div>
        <p style="color: #64748b; font-size: 12px; line-height: 1.5;">
          If you did not create a DeepCoin account, you can safely ignore this email.
          <br>
          Link: <a href="{verify_url}" style="color: #3b82f6;">{verify_url}</a>
        </p>
      </div>
    </body>
    </html>
    """
    return await _send(to_email, "Verify your DeepCoin email address", html)


async def send_password_reset_email(to_email: str, token: str) -> bool:
    """
    Send a 1-hour password reset link.

    WHAT:
        Constructs a link of the form:
            {APP_URL}/reset-password?token={token}

    WHY 1 hour (shorter than verification):
        A password reset link is higher-stakes — if someone intercepted
        your email to request a reset, they should have a narrow window.

    Args:
        to_email: Destination email address.
        token:    Opaque random token (URL-safe, stored as hash in DB).

    Returns:
        True if delivery succeeded (or dev-mode skip), False on send error.
    """
    reset_url = f"{_APP_URL}/reset-password?token={token}"

    html = f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family: Arial, sans-serif; background: #0a0f2c; color: #e2e8f0; padding: 40px;">
      <div style="max-width: 520px; margin: auto; background: #131a3a; border-radius: 12px; padding: 40px;">
        <h1 style="color: #3b82f6; margin-bottom: 8px;">DeepCoin</h1>
        <p style="color: #94a3b8; font-size: 13px;">Archaeological Coin Intelligence Platform</p>
        <hr style="border-color: #1e2d52; margin: 24px 0;">
        <h2 style="font-size: 20px; margin-bottom: 12px;">Reset your password</h2>
        <p style="color: #94a3b8; line-height: 1.6;">
          We received a request to reset your DeepCoin password.
          Click below to set a new password. This link expires in
          <strong style="color: #e2e8f0;">1 hour</strong>.
        </p>
        <div style="text-align: center; margin: 32px 0;">
          <a href="{reset_url}"
             style="background: #3b82f6; color: white; padding: 14px 32px; border-radius: 8px;
                    text-decoration: none; font-weight: bold; display: inline-block;">
            Reset Password
          </a>
        </div>
        <p style="color: #64748b; font-size: 12px; line-height: 1.5;">
          If you did not request a password reset, you can safely ignore this email.
          Your password will <strong>not</strong> change.
          <br>
          Link: <a href="{reset_url}" style="color: #3b82f6;">{reset_url}</a>
        </p>
      </div>
    </body>
    </html>
    """
    return await _send(to_email, "Reset your DeepCoin password", html)
