"""
src/api/auth/utils.py
=====================
Cryptographic utilities for authentication.

FUNCTIONS
---------
    hash_password(plain)         → bcrypt hash string
    verify_password(plain, hash) → bool
    create_access_token(data)    → short-lived JWT string
    create_refresh_token()       → (raw_token, sha256_hash, expires_at)
    decode_token(token)          → payload dict  (raises HTTPException on failure)

DESIGN DECISIONS
----------------
    bcrypt work factor = 12:
        bcrypt is deliberately slow (by design). Work factor 12 means ~250ms
        to hash one password on modern hardware. Fast enough for logins; slow
        enough that brute-forcing a leaked hash takes years. Never use MD5/SHA
        for passwords — they are cryptographic hash functions, not KDFs.

    JWT algorithm = HS256:
        HMAC-SHA256. Symmetric (sign + verify with the same JWT_SECRET).
        Symmetric is fine for a monolith where only our own server needs to
        verify tokens. Use RS256 (asymmetric) only when external services need
        to verify tokens without trusting them with the secret.

    Short access token expiry (15 min default):
        If an access token is stolen (e.g. via XSS), it is valid for at most
        15 minutes. The refresh token (7 days, stored in httpOnly cookie) is
        used to silently obtain a new access token.

    Refresh token stored as SHA-256 hash:
        We store hash(token) in the database. If the DB is leaked, attackers
        cannot reconstruct the token. The raw token is returned once (to be
        placed in an httpOnly cookie) and never stored.

    Secrets from environment:
        JWT_SECRET must be set via environment variable.
        We raise at startup if it equals the placeholder value in production.
        In dev mode (ENV != "production") the placeholder is allowed so that
        a fresh clone needs zero .env setup to run locally.
"""
from __future__ import annotations

import hashlib
import os
import secrets
import logging
from datetime import datetime, timezone, timedelta

from jose import jwt, JWTError
from passlib.context import CryptContext
from fastapi import HTTPException, status

logger = logging.getLogger(__name__)

# ── Config ────────────────────────────────────────────────────────────────────

_JWT_SECRET: str = os.getenv("JWT_SECRET", "CHANGE_ME_DO_NOT_USE_IN_PRODUCTION")
_JWT_ALGORITHM: str = "HS256"
_ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "15"))
_REFRESH_TOKEN_EXPIRE_DAYS: int = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", "7"))

# Warn loudly if the default secret is used in production
_ENV = os.getenv("ENV", "development")
if _ENV == "production" and _JWT_SECRET == "CHANGE_ME_DO_NOT_USE_IN_PRODUCTION":
    raise RuntimeError(
        "JWT_SECRET environment variable must be set to a random 64-char secret in production. "
        "Generate one with: python -c \"import secrets; print(secrets.token_hex(32))\""
    )

# ── Password hashing ─────────────────────────────────────────────────────────

_pwd_context = CryptContext(
    schemes=["bcrypt"],
    deprecated="auto",
    bcrypt__rounds=12,         # work factor — increase to 13 if GPU attacks become common
)


def hash_password(plain_password: str) -> str:
    """
    Hash a plain-text password using bcrypt (work factor 12).

    WHAT:
        Returns a bcrypt hash string of the form "$2b$12$<22-char salt><31-char hash>".
        The salt is randomly generated by passlib on every call — two identical
        passwords produce different hashes.

    WHY bcrypt:
        Intentionally slow (CPU-hard) KDF. Cannot be accelerated on GPUs or
        ASICs the way MD5/SHA can. The stored hash contains the algorithm,
        work factor, and salt, so future upgrades (higher work factor) are
        backward-compatible via passlib's `deprecated="auto"`.

    Args:
        plain_password: The raw password string from the API request.

    Returns:
        A bcrypt hash string safe to store in the database.
    """
    return _pwd_context.hash(plain_password)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verify a plain-text password against a stored bcrypt hash.

    Uses passlib's constant-time comparison internally (no timing attack risk).

    Args:
        plain_password:   Raw password from login request.
        hashed_password:  Value stored in users.hashed_password column.

    Returns:
        True if they match, False otherwise.
    """
    return _pwd_context.verify(plain_password, hashed_password)


# ── JWT access token ──────────────────────────────────────────────────────────

def create_access_token(data: dict, expire_minutes: int | None = None) -> str:
    """
    Create a signed JWT access token.

    WHAT:
        Creates a JWT with the provided payload plus:
            sub  — subject (must be present in `data` as the user ID)
            iat  — issued-at timestamp
            exp  — expiry timestamp (now + expire_minutes)
            type — "access" (to distinguish from refresh tokens)

    WHY short expiry:
        Access tokens are sent in the Authorization header on every request.
        If stolen (e.g. via XSS), they should expire quickly. The refresh
        token (httpOnly cookie, 7-day expiry) silently renews the access token.

    Args:
        data:           Dict must include "sub" (user ID string) and optionally
                        "role", "email", "status".
        expire_minutes: Override the default expiry. Only tests should set this.

    Returns:
        Signed JWT string.
    """
    minutes = expire_minutes if expire_minutes is not None else _ACCESS_TOKEN_EXPIRE_MINUTES
    expires = datetime.now(timezone.utc) + timedelta(minutes=minutes)

    payload = {
        **data,
        "iat":  datetime.now(timezone.utc),
        "exp":  expires,
        "type": "access",
    }
    return jwt.encode(payload, _JWT_SECRET, algorithm=_JWT_ALGORITHM)


# ── Refresh token ─────────────────────────────────────────────────────────────

def create_refresh_token() -> tuple[str, str, datetime]:
    """
    Generate a secure random refresh token.

    WHAT:
        Returns a tuple of (raw_token, token_hash, expires_at):
            raw_token  — 64 random bytes as a hex string (128 chars). Return
                         this to the client in an httpOnly cookie.
            token_hash — SHA-256(raw_token) as a hex string. Store THIS in
                         the database, never the raw token.
            expires_at — timezone-aware UTC datetime for the expiry column.

    WHY not a JWT:
        Refresh tokens are opaque credentials. They don't need to carry any
        claims (that's the access token's job). An opaque random token is
        harder to forge than a JWT if the signing secret is ever compromised.

    Returns:
        Tuple[raw_token, token_hash, expires_at]
    """
    raw_token = secrets.token_hex(64)                         # 128 hex chars = 512 bits entropy
    token_hash = hashlib.sha256(raw_token.encode()).hexdigest()  # 64-char hex
    expires_at = datetime.now(timezone.utc) + timedelta(days=_REFRESH_TOKEN_EXPIRE_DAYS)
    return raw_token, token_hash, expires_at


# ── Token decoding ────────────────────────────────────────────────────────────

def decode_token(token: str) -> dict:
    """
    Decode and validate a JWT, returning its payload dict.

    WHAT:
        1. Verifies the signature against JWT_SECRET.
        2. Verifies the `exp` claim (not expired).
        3. Verifies the `type` claim == "access" (rejects refresh tokens presented as access tokens).

    WHY we check `type`:
        A malicious client could present a refresh token (which is not a JWT in
        our design, but is in some designs) or a token with `type=""reverse_access"`
        as an access token. The type check is a defence-in-depth guard.

    Args:
        token: The raw JWT string from the Authorization header.

    Raises:
        HTTPException(401): if the token is invalid, expired, or has wrong type.

    Returns:
        Decoded payload dict (includes sub, role, email, exp, iat, type).
    """
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, _JWT_SECRET, algorithms=[_JWT_ALGORITHM])
    except JWTError as exc:
        logger.debug("JWT decode failed: %s", exc)
        raise credentials_exception from exc

    if payload.get("type") != "access":
        logger.debug("JWT presented with wrong type: %s", payload.get("type"))
        raise credentials_exception

    if not payload.get("sub"):
        raise credentials_exception

    return payload
