import os
import json
import re

def update_json(filepath, lang):
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    if "AnalysisPanel" not in data:
        data["AnalysisPanel"] = {}
    
    if "HistoryDetail" not in data:
        data["HistoryDetail"] = {}

    fr = lang == "fr"

    ap = data["AnalysisPanel"]
    ap["gradcamTitle"] = "Explication Visuelle (Grad-CAM)" if fr else "Grad-CAM — CNN Visual Explanation"
    ap["gradcamAlt"] = "Carte d'activation Grad-CAM" if fr else "Grad-CAM activation heatmap"
    ap["gradcamRegions"] = "Les zones soulignées en " if fr else "Regions highlighted in "
    ap["gradcamRed"] = "rouge/jaune" if fr else "red/yellow"
    ap["gradcamPixels"] = " sont les pixels que le CNN a le plus pondérés pour sélectionner " if fr else " are the pixels the CNN weighted most when selecting "
    ap["gradcamAsTop"] = " comme meilleure correspondance. Les zones en " if fr else " as the top match. Areas shown in "
    ap["gradcamBlue"] = "bleu foncé" if fr else "dark blue"
    ap["gradcamContrib"] = " ont peu contribué à la décision." if fr else " contributed little to the decision."
    ap["gradcamScaleLow"] = "Faible" if fr else "Low"
    ap["gradcamScaleHigh"] = "Élevé" if fr else "High"
    ap["gradcamGenerated"] = "Généré par Grad-CAM++ sur EfficientNet-B3 étape-5 (carte de caractéristiques 19×19, résolution 3,6× plus fine). Superposition sur l'image originale (pré-TTA)." if fr else "Generated by Grad-CAM++ on EfficientNet-B3 stage-5 (19×19 feature map, 3.6× finer spatial resolution than the final layer). Overlay is computed on the original (pre-TTA) image."
    
    ap["exploreRecord"] = "Explorer la notice scientifique officielle" if fr else "Explore the official scholarly record"
    ap["askAi"] = "Demander à DeepCoin AI à propos de " if fr else "Ask DeepCoin AI about "
    ap["deepDive"] = "Plongez dans l'histoire, l'iconographie et la numismatique" if fr else "Deep-dive into history, iconography & numismatic significance"
    
    ap["classificationCnn"] = "Classification CNN" if fr else "Classification CNN"
    ap["typeIdentified"] = "Type Identifié" if fr else "Type Identified"
    ap["inferenceTime"] = "Inférence :" if fr else "Inference:"
    ap["ttaYes"] = "Oui" if fr else "Yes"
    ap["ttaNo"] = "Non" if fr else "No"
    ap["ttaAgree"] = "d'accord" if fr else "agree"
    ap["ttaPasses"] = "passages" if fr else "passes"
    ap["allLinksOpen"] = "Tous les liens ↗ s'ouvrent dans un nouvel onglet. Le site corpus-nummorum.eu peut prendre quelques secondes pour répondre." if fr else "All ↗ links open corpus-nummorum.eu in a new tab. The site may take a few seconds to respond."
    ap["downloadPdf"] = "Télécharger le rapport PDF" if fr else "Download PDF Report"

    hd = data["HistoryDetail"]
    hd["viewCn"] = "Voir sur Corpus Nummorum" if fr else "View on Corpus Nummorum"
    hd["copyLink"] = "Copier le lien" if fr else "Copy link"
    hd["historian"] = "Historien" if fr else "Historian"
    hd["validator"] = "Validateur" if fr else "Validator"
    hd["investigator"] = "Enquêteur" if fr else "Investigator"
    hd["highConf"] = "Confiance élevée" if fr else "High confidence"
    hd["ttaConsensus"] = "Consensus TTA" if fr else "TTA consensus"
    hd["moderateMatch"] = "Correspondance moyenne" if fr else "Moderate match"
    hd["lowVisual"] = "Signal visuel faible" if fr else "Low visual signal"
    hd["scholarlyRecord"] = "Fiche scientifique :" if fr else "Scholarly record:"
    hd["agree"] = "d'accord" if fr else "agree"
    hd["passes"] = "passages" if fr else "passes"

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

update_json("frontend/messages/en.json", "en")
update_json("frontend/messages/fr.json", "fr")
