"""
src/api/db/models.py
====================
SQLAlchemy 2 ORM models — the single source of truth for the database schema.

TABLE OVERVIEW
--------------
    users               — registered accounts with roles
    classifications     — one row per coin analysis (replaces SQLite store)
    feedback            — "mark as wrong" corrections (replaces embedded JSON)
    audit_log           — immutable record of every mutation
    email_verifications — 24-hour tokens for email confirmation
    refresh_tokens      — stored (hashed) refresh tokens for logout + revocation

DESIGN DECISIONS
----------------
    UUIDs as PKs:
        Row counts never overflow. Safe to generate client-side if needed.
        server_default=func.gen_random_uuid() is generated by PostgreSQL, not Python,
        so there's no risk of UUID collision from concurrent inserts.

    TIMESTAMPTZ (timezone-aware):
        All timestamps stored as UTC with timezone info. Never use TIMESTAMP (naive)
        in a multi-region or multi-user system — naive timestamps are ambiguous.

    JSONB for payload:
        The full ClassifyResponse dict is stored as JSONB so we can query into it
        (e.g. "all records where payload->>'route_taken' = 'historian'") without
        deserialising in Python. GIN index on payload enables fast JSON path queries.

    Relationships:
        Declared with back_populates for bidirectional navigation.
        lazy="select" + async sessions means we explicitly use selectinload() or
        joinedload() in queries — we never rely on lazy loading (which is illegal
        in async SQLAlchemy).

    ON DELETE SET NULL vs CASCADE:
        user_id FKs on classifications/feedback/audit_log use SET NULL so that
        deleting a user account does not cascade-delete their research history.
        classification_id FK on feedback uses CASCADE — no orphan feedback rows.
"""
from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean, DateTime, Enum, Float, ForeignKey, Index,
    String, Text, func
)
from sqlalchemy.dialects.postgresql import JSONB, UUID, INET
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.api.db.base import Base


# ── Python Enums (used as SQLAlchemy column types) ────────────────────────────

class UserRole(str, enum.Enum):
    """
    RBAC roles in ascending privilege order.

    admin    — full access to everything including user management
    curator  — can review, edit, and export classifications; no user management
    analyst  — can classify and view own history; can leave reviews
    """
    admin    = "admin"
    curator  = "curator"
    analyst  = "analyst"


class UserStatus(str, enum.Enum):
    """
    Account lifecycle states.

    pending   — registered but email not yet verified
    active    — email verified, can use the platform
    suspended — admin-suspended, cannot log in
    """
    pending   = "pending"
    active    = "active"
    suspended = "suspended"


# ── User ──────────────────────────────────────────────────────────────────────

class User(Base):
    """
    Registered platform account.

    WHY display_name separate from email:
        Museums may want to show "Dr. Ahmed Chaieb" in the UI instead of
        "a.chaieb@esprit.tn". display_name is optional and defaults to the
        email prefix.

    WHY last_login_at:
        Admin dashboard shows inactive accounts (last_login > 90 days).
        Useful for pruning test accounts before moving to production.
    """
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(100), nullable=True)

    role: Mapped[UserRole] = mapped_column(
        Enum(UserRole, name="user_role"), nullable=False, default=UserRole.analyst,
        server_default=UserRole.analyst.value,
    )
    status: Mapped[UserStatus] = mapped_column(
        Enum(UserStatus, name="user_status"), nullable=False, default=UserStatus.pending,
        server_default=UserStatus.pending.value,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        server_default=func.now(), onupdate=func.now()
    )
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    email_verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Relationships ──
    classifications:   Mapped[list["Classification"]]   = relationship(back_populates="user", lazy="select")
    feedback:          Mapped[list["Feedback"]]          = relationship(back_populates="user", lazy="select")
    audit_log_entries: Mapped[list["AuditLog"]]          = relationship(back_populates="user", lazy="select")
    email_verifications: Mapped[list["EmailVerification"]] = relationship(back_populates="user", lazy="select", cascade="all, delete-orphan")
    refresh_tokens:    Mapped[list["RefreshToken"]]      = relationship(back_populates="user", lazy="select", cascade="all, delete-orphan")
    chat_sessions:     Mapped[list["ChatSession"]]       = relationship(back_populates="user", lazy="select", cascade="all, delete-orphan")
    coins:             Mapped[list["Coin"]]              = relationship(back_populates="user", lazy="select")

    def __repr__(self) -> str:
        return f"<User id={self.id[:8]} email={self.email} role={self.role.value}>"


# ── Classification ────────────────────────────────────────────────────────────

class Classification(Base):
    """
    One complete coin analysis result.

    Replaces the SQLite `classifications` table in `_store.py`.

    WHY user_id is nullable:
        We want to allow guest classifications (no login required) so that
        new visitors can try the tool before registering. user_id=NULL means
        a guest submission. The admin can still see all records.

    WHY JSONB payload:
        The full ClassifyResponse structure evolves as we add fields.
        Storing as JSONB means old records are never broken by schema changes.
        The indexed scalar columns (label, confidence, route_taken) cover all
        query patterns; the JSONB payload is retrieved for display only.
    """
    __tablename__ = "classifications"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )
    label: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    route_taken: Mapped[str] = mapped_column(String(50), nullable=False)
    image_filename: Mapped[str | None] = mapped_column(String(255), nullable=True)
    pdf_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # ── Relationships ──
    user:     Mapped["User | None"] = relationship(back_populates="classifications")
    feedback: Mapped[list["Feedback"]] = relationship(
        back_populates="classification", lazy="select", cascade="all, delete-orphan"
    )

    # ── Composite index: user + time (most common query pattern) ──
    __table_args__ = (
        Index("ix_classifications_user_ts", "user_id", "timestamp"),
    )

    def __repr__(self) -> str:
        return f"<Classification id={self.id[:8]} label={self.label} conf={self.confidence:.2f}>"


# ── Feedback ──────────────────────────────────────────────────────────────────

class Feedback(Base):
    """
    User correction attached to a Classification ("mark as wrong").

    Replaces the `feedback` sub-dict previously embedded in the JSONB payload.

    WHY a proper table instead of embedded JSON:
        - Can be queried independently (e.g. "all disputed records for label 1015")
        - Can be joined against users to show who submitted the correction
        - Can be filtered by date for active learning batch exports
        - Cannot be accidentally overwritten by a payload update

    WHY ON DELETE CASCADE:
        If a classification record is deleted, its feedback rows have no meaning
        and should be removed automatically.
    """
    __tablename__ = "feedback"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    classification_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("classifications.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    user_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    correct_type_id: Mapped[str] = mapped_column(String(50), nullable=False)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # ── Relationships ──
    classification: Mapped["Classification"] = relationship(back_populates="feedback")
    user:           Mapped["User | None"]    = relationship(back_populates="feedback")

    def __repr__(self) -> str:
        return f"<Feedback id={self.id[:8]} correct_type={self.correct_type_id}>"


# ── AuditLog ──────────────────────────────────────────────────────────────────

class AuditLog(Base):
    """
    Immutable record of every significant mutation in the system.

    WHY immutable:
        Audit logs must never be updated or deleted — they are the legal record
        of "who did what when". The table has no UPDATE route and no CASCADE DELETE.

    WHY not a separate service:
        For a single-worker PFE deployment, writing to an audit_log table inside
        the same transaction is correct.  In a microservices architecture you'd
        publish to a message queue instead, but that's overkill here.

    Action naming convention: "{resource}.{verb}"
        "user.register"       — new account created
        "user.login"          — successful login
        "user.login_failed"   — bad password attempt
        "user.role_change"    — admin changed someone's role
        "user.suspend"        — admin suspended account
        "classify"            — coin analysis completed
        "record.delete"       — history record deleted
        "feedback.submit"     — mark-as-wrong submitted
        "feedback.delete"     — feedback removed
    """
    __tablename__ = "audit_log"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    action: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    resource_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    resource_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    payload: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)  # IPv6 max 45 chars
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )

    # ── Relationships ──
    user: Mapped["User | None"] = relationship(back_populates="audit_log_entries")

    def __repr__(self) -> str:
        return f"<AuditLog action={self.action} user={self.user_id}>"


# ── EmailVerification ─────────────────────────────────────────────────────────

class EmailVerification(Base):
    """
    One-time token sent to verify a user's email address.

    WHY 24-hour expiry:
        Short enough to prevent link reuse if the email is forwarded.
        Long enough for a user who checks email once a day.

    WHY used_at instead of deleting the row:
        Keeping used tokens lets us detect replay attacks ("this token was
        already used 5 minutes ago — possible attack").
        We can run a cron to delete tokens older than 48 hours.

    WHY CASCADE on user_id:
        If a user is deleted (e.g. GDPR purge), all their verification tokens
        should also be deleted.
    """
    __tablename__ = "email_verifications"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    token: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Relationships ──
    user: Mapped["User"] = relationship(back_populates="email_verifications")

    def __repr__(self) -> str:
        return f"<EmailVerification user={self.user_id} used={self.used_at is not None}>"


# ── RefreshToken ──────────────────────────────────────────────────────────────

class RefreshToken(Base):
    """
    Persisted refresh token record enabling logout and revocation.

    WHY store the hash, not the token:
        If the refresh_tokens table is compromised, attackers cannot use the
        hashes directly — they would need the original token values.
        We store SHA-256(token) and compare on refresh.

    WHY revoked_at instead of deleting on logout:
        Soft-revocation lets us detect if a revoked token is presented again —
        a sign that it was stolen and the legitimate user has since logged out.
        A scheduled job can hard-delete rows where revoked_at < (now - 30 days).

    WHY CASCADE:
        Deleting a user deletes all their refresh tokens, enforcing a full logout.
    """
    __tablename__ = "refresh_tokens"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    token_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)

    # ── Relationships ──
    user: Mapped["User"] = relationship(back_populates="refresh_tokens")

    def __repr__(self) -> str:
        return f"<RefreshToken user={self.user_id} revoked={self.revoked_at is not None}>"


# ── ChatSession ──────────────────────────────────────────────────────────────────────────

class ChatSession(Base):
    """
    One AI chat conversation saved by a user.

    WHY store messages as JSONB:
        Chat messages are a variable-length array of {role, content, sources, provider}.
        JSONB lets us store the full structure without needing a separate
        messages table.  Indexing isn't required on individual messages —
        we always load an entire session at once.

    WHY title is the first user message (truncated):
        Users need to recognise their past conversations at a glance.
        Storing the first user message as the title is the universal pattern
        (used by ChatGPT, Claude, Gemini).  We cap it at 200 chars.

    WHY CASCADE on user_id:
        If a user deletes their account (GDPR purge), all their chat history
        should be destroyed automatically — no orphan rows.
    """
    __tablename__ = "chat_sessions"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    messages: Mapped[list] = mapped_column(JSONB, nullable=False, default=list, server_default="[]",)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        server_default=func.now(), onupdate=func.now()
    )

    # ── Relationships ──
    user: Mapped["User"] = relationship(back_populates="chat_sessions")

    def __repr__(self) -> str:
        return f"<ChatSession id={self.id[:8]} user={self.user_id[:8]} title={self.title[:30]}"


class EmailLog(Base):
    """
    Audit log of all outbound emails (verification, reset, marketing).
    Provides non-repudiation and delivery tracking.
    """
    __tablename__ = "email_logs"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=func.gen_random_uuid())
    user_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    to_email: Mapped[str] = mapped_column(String(255), nullable=False)
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="sent")
    error_message: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now(), index=True)

    # Relationship
    user: Mapped["User"] = relationship()

    def __repr__(self) -> str:
        return f"<EmailLog {self.to_email} subject={self.subject[:20]}>"


# ── Coin ──────────────────────────────────────────────────────────────────────

class Coin(Base):
    """
    Physical coin inventory and dataset tracking.
    
    Tracks whether a coin is part of the CNN training set or was uploaded
    by an admin manually. The AI helps pre-fill the metadata (duplicate detection,
    nonsense rejection) before insertion.
    """
    __tablename__ = "coins"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    cn_type_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    image_path: Mapped[str] = mapped_column(String(512), nullable=False)
    
    # Metadata fields pre-filled by AI
    material: Mapped[str | None] = mapped_column(String(100), nullable=True)
    weight: Mapped[float | None] = mapped_column(Float, nullable=True)
    diameter: Mapped[float | None] = mapped_column(Float, nullable=True)
    
    # Training & Audit states
    in_training_set: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default="false")
    added_by_admin: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default="false")
    ai_validated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default="false")
    
    # Who added it
    user_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        server_default=func.now(), onupdate=func.now()
    )

    # ── Relationships ──
    user: Mapped["User | None"] = relationship(back_populates="coins")
    
    def __repr__(self) -> str:
        return f"<Coin id={self.id[:8]} type={self.cn_type_id} training={self.in_training_set}>"

