"""Add Coin table

Revision ID: 18c068858fd0
Revises: 003_email_logs
Create Date: 2026-04-23 16:23:23.384570+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c068858fd0'
down_revision: Union[str, None] = '003_email_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cn_type_id', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('in_training_set', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('added_by_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_validated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coins_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coins'))
    )
    op.create_index(op.f('ix_coins_cn_type_id'), 'coins', ['cn_type_id'], unique=False)
    op.create_index(op.f('ix_coins_created_at'), 'coins', ['created_at'], unique=False)
    op.create_index(op.f('ix_coins_user_id'), 'coins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_user_id'), table_name='coins')
    op.drop_index(op.f('ix_coins_created_at'), table_name='coins')
    op.drop_index(op.f('ix_coins_cn_type_id'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
