"""
The Editor-in-Chief Agent - Synthesis Specialist
Compiles all agent outputs into professional Markdown/PDF reports.
"""

from typing import Dict
from datetime import datetime


class EditorInChief:
    """
    Aggregates outputs from all agents and generates final report.
    Adds verification badges and citations.
    """
    
    def synthesize(self, state: Dict) -> str:
        """
        Generate final report from LangGraph state.
        
        Args:
            state: Complete workflow state with all agent outputs
        
        Returns:
            Markdown-formatted report string
        """
        cnn = state["cnn_prediction"]
        route = state.get("route_taken", "unknown")
        
        # Build report sections
        report = self._generate_header(cnn)
        report += self._generate_classification_section(cnn)
        
        if route == "investigator":
            report += self._generate_investigator_section(state["visual_description"])
        elif route == "validator":
            report += self._generate_validator_section(state["validation_result"])
        elif route == "historian":
            report += self._generate_historian_section(state["historical_context"])
        
        report += self._generate_footer(state)
        
        return report
    
    def _generate_header(self, cnn: Dict) -> str:
        """Generate report header."""
        return f"""# DeepCoin Classification Report

**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Coin ID**: {cnn.get('class', 'Unknown')}  
**Classification**: {cnn.get('label', 'Unknown')}  
**Confidence**: {cnn.get('confidence', 0.0):.2%}

---

"""
    
    def _generate_classification_section(self, cnn: Dict) -> str:
        """Generate CNN prediction section."""
        return f"""## 🧠 Deep Learning Classification

**Model**: EfficientNet-B3 (Fine-tuned on 438 coin types)  
**Prediction**: {cnn.get('label', 'Unknown')}  
**Confidence Score**: {cnn.get('confidence', 0.0):.2%}

"""
    
    def _generate_investigator_section(self, description: str) -> str:
        """Generate Visual Investigator section."""
        return f"""## 🔍 Visual Investigation (Low Confidence)

**AI Description**: {description}

*Note: This coin exhibited high wear/corrosion. Visual analysis performed by GPT-4o Vision.*

"""
    
    def _generate_validator_section(self, validation: Dict) -> str:
        """Generate Forensic Validator section."""
        status = validation.get("validation_status", "unknown")
        anomalies = validation.get("anomalies", [])
        
        badge = "✅ **Verified**" if status == "approved" else "⚠️ **Requires Review**"
        
        report = f"""## ⚖️ Forensic Validation

{badge}

**Status**: {status.upper()}

"""
        if anomalies:
            report += "**Anomalies Detected**:\n"
            for anomaly in anomalies:
                report += f"- {anomaly}\n"
        
        return report + "\n"
    
    def _generate_historian_section(self, context: str) -> str:
        """Generate Historian section."""
        # TODO: Parse structured historical data
        return f"""## 📚 Historical Context

{context}

"""
    
    def _generate_footer(self, state: Dict) -> str:
        """Generate report footer with metadata."""
        footer = "\n---\n\n## Verification\n\n"
        
        if state.get("human_approved"):
            footer += "✅ **Expert Verified** - This classification was reviewed and approved by a numismatic expert.\n\n"
        
        footer += """
**Generated by**: DeepCoin-Core v1.0  
**Technology**: EfficientNet-B3 + LangGraph Multi-Agent System  
**Institution**: ESPRIT School of Engineering  
**Company**: YEBNI - Information & Communication  
"""
        
        return footer
    
    def to_pdf(self, markdown_content: str, output_path: str):
        """Convert Markdown report to PDF."""
        # TODO: Implement in Phase 5 using markdown2pdf or weasyprint
        pass


if __name__ == "__main__":
    print("📝 Editor-in-Chief Agent - Ready for Phase 5")
